### PR TITLE
[JENKINS-33343] Update to parent POM 2.3

### PR DESCRIPTION
**Pull request by andresrc**
See [JENKINS-33343](https://issues.jenkins-ci.org/browse/JENKINS-33343)

Includes:
* [x] Update parent POM to version 2.3
* [x] Fix javadoc when building on Java 8
* [x] Findbugs.
* [x] Fix build (including Findbugs) against 1.642.2 (PCT scenario).
* [x] Migrate tests to JTH 2.1

Modifications in zip files are related to local data clean up for a situation analogous to https://github.com/jenkinsci/jenkins/pull/2071 when building using Java 8.

### CODE REVIEW

**Comment by andresrc** [comment]
@reviewbybees

**Comment by jglick** [comment]
Intended to supersede #34?

**Comment by jglick** [comment]
What about #22 and #31?

**Comment by kwhetstone** [comment]
Yeah, updating this plugin was a nightmare.  That's why originally I didn't move the plugin beyond 1.580.1.  To run without errors (even after the upgrade), #31 will have to be merged in.

**Comment by andresrc** [comment]
Ups, well it supersedes all three PRs. To @kwhetstone, @oleg-nenashev, @rsandell : My apologies, I jumped head first.

I will be more careful next time, I promise.

**Comment by andresrc** [comment]
@kwhetstone the changes in the zips were to avoid having to update the baseline.

**Comment by kwhetstone** [comment]
Awesome, looks great :bee:

**Comment by jglick** [comment]
:bug: this does _not_ address the `hpi:run` problem identified and fixed in #31.

**Comment by jglick** [comment]
Never mind, :bee: that is better handled by https://github.com/jenkinsci/maven-hpi-plugin/pull/29.

**Comment by andresrc** [comment]
@jglick Should we wait for release of https://github.com/jenkinsci/maven-hpi-plugin/pull/29 before merging?

Anyway when that happens I'll bump that and JTH version in plugin-pom.

**Comment by jglick** [comment]
I will propose an integration of the plugin.

**Pull request merged**
