### PR TITLE
URL encode fix for All Failed Tests sections

### PR DESCRIPTION
**Pull request by ahadalioglu**
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by timja** [comment]
Hi please test the solution and provide the testing done in the PR description

**Comment by basil** [comment]
https://ci.jenkins.io/job/Plugins/job/junit-plugin/job/PR-664/2/testReport/hudson.tasks.junit/TestResultLinksTest/testFailureLinks/ shows a new test failure with this PR:

> 404 Not Found for http://localhost:42811/jenkins/job/taqueria/1/testReport/tacoshack.meals%2FNachosTest%2FtestBeanDip%2F

That looks suspicious because the / is incorrectly encoded as %2F. Per [the Javadoc](https://javadoc.jenkins.io/hudson/Util.html#rawEncode(java.lang.String)):

> Note that slash (/) is encoded, so the given string should be a single path component used in constructing a URL. 

So `Util#rawEncode` should be called on each component of the path internally within `getRelativePathFrom`, rather than on the return value of `getRelativePathFrom` which contains the entire path.

**Comment by ahadalioglu** [comment]
I guess I've fixed incorrectly encoded slash issues, but now it gives `500 Server Error`
Any ideas, what might be the issue?

**Comment by basil** [comment]
> Any ideas, what might be the issue?

https://ci.jenkins.io/job/Plugins/job/junit-plugin/job/PR-664/9/testReport/junit/hudson.tasks.junit/CaseResultTest/linux_21___Build__linux_21____noPopUpsWhenExpandingATest/ I suppose:

```
org.apache.commons.jelly.JellyTagException: file:/home/jenkins/agent/workspace/Plugins_junit-plugin_PR-664/target/classes/hudson/tasks/test/MetaTabulatedResult/body.jelly:47:101: <j:invokeStatic> Could not load class: hudson.Util. Reason: java.lang.NoSuchMethodException: hudson.Util.rawEncode(java.lang.Object)
```

**Pull request closed without merging**
