### PR TITLE
Add support and access to junit properties

### PR DESCRIPTION
**Pull request by thomas-dee**
It would be great if the testsuite/properties tags would be accessible.

### CODE REVIEW

**Comment by timja** [comment]
Needs a unit test, some more expansion on the use case would be useful

**Comment by apopescu99** [comment]
Hello, will this change be included in the junit-plugin soon? Thank you!

**Comment by timja** [comment]
not without the review comment being addressed

**Comment by mPokornyETM** [comment]
> It would be great if the testsuite/properties tags would be accessible.

It will be great when you show this properties somewhere in test-suite page

**Comment by timja** [comment]
Added in https://github.com/jenkinsci/junit-plugin/pull/541

**Pull request closed without merging**
