### PR TITLE
Add UI tests

### PR DESCRIPTION
**Pull request by uhafner**
Temporary followup for #342 to see if all tests pass in CI with latest release of junit-plugin.

### CODE REVIEW

**Comment by timja** [comment]
I touched it, maybe it'll work

**Comment by timja** [comment]
I'm happy to give you write access for playing with this?

**Comment by uhafner** [comment]
I don't want to use additional resources on Jenkins.ci :-)

**Comment by uhafner** [comment]
But maybe it makes sense to have permissions then I can push in a branch here so that the actions will run. The setup is similar to the warnings plugin.

**Comment by timja** [comment]
Gave you write access

**Pull request closed without merging**
