### PR TITLE
Don't error on old test reports

### PR DESCRIPTION
**Pull request by timja**
This is an outdated feature that doesn't reflect modern build tools that won't rebuild if all the inputs are the same (and they aren't forced to rebuild)

A multitude of hacks for gradle that are no longer needed after this:
https://stackoverflow.com/questions/13879667/how-to-fix-test-reports-were-found-but-none-of-them-are-new-did-tests-run-in

Seems like there was no test coverage for this and I don't think it makes sense to add any for a non feature

Fixes https://github.com/jenkinsci/junit-plugin/issues/201

### CODE REVIEW

**Comment by raul-arabaolaza** [comment]
@timja I believe this change broke https://github.com/jenkinsci/maven-plugin/blob/0f600837dbea3d8a86984f34f9cc7eb2e24950da/src/test/java/hudson/maven/reporters/SurefireArchiverUnitTest.java#L175 which was created due to https://issues.jenkins.io/browse/JENKINS-31524 which I believe is still a valid concern.

My knowledge on the internals here is zero so I believe you are the best one to evaluate if JENKINS-31524 is still a concern or is no more relevant

**Comment by timja** [comment]
Hi 

I've had a bit of a look and can't say I really understand the maven plugin change that was done.
I would've thought the change here would only help in the reported bug case but not the easiest to understand.

The safest way would be for the user to use separate directories anyway.

**Comment by raul-arabaolaza** [comment]
Thanks @timja I am on the same situation, will dig deeper.

**Comment by jtnord** [comment]
But if nothing is rebuilt, and hence the tests are not run, (and the file is outdated) why would we want to report the tests as run / passing in the UI when they are not run?

Because the tests are not run how do you know they pass.  For example a test that fails if the date > 19-03-2022  would pass today.
If gradle or whatever never re team that test as the production and test code never changes we would report it tomorrow as passing. (And it would not have passed if ran).
This leads to the issue that people would see a failing test in thier PR, (when compared to the last build on the mainline branch) which with good reason they could assume was due to thier PR.

Iirc (unable to check now) but this issue reported was always fixable if the user wanted it by setting a system property?

The issue we also have now IIUC is that we will also report tests that no longer exist.
E.g do not clean target/ before running tests and remove a Test file?

**Comment by jtnord** [comment]
> This fundamentally did not work with gradle's test results previously without work arounds.

does it work now with `maven` (`mvn test`) for example then `rm -fr src/test/java/myTest`   (the surefire result for test `MyTest` will now remain and be constantly reported until you wipe out the workspace).

> This change means that the plugin reports test results that are there. If you don't want them to be reported then you need to not have them there.

And that is the issue - the plugin should report tests that *ran*

**Comment by jglick** [comment]
This appears to leave behind an unused parameter `buildTime` as well as an obsolete comment https://github.com/jenkinsci/junit-plugin/blob/86b06fd8de7396664cd59cd7400b33414181537a/src/main/java/hudson/tasks/junit/TestResult.java#L142-L143 IIUC?

**Pull request merged**
