### PR TITLE
[JENKINS-27395] Add a junitResults step

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-27395](https://issues.jenkins-ci.org/browse/JENKINS-27395)

Subsumes #64 

This is still a work-in-progress - I wanted to get the initial work up for review to see if I'm going down the right path. 

- [ ] Tests of `junitResults` step
- [ ] API for pulling all test results for a given name from the `TestResultAction`
- [ ] Probably some way of not displaying the test run name when it's auto-generated - and perhaps a better way to auto-generate than just using the `FlowNode.getId()`
- [ ] Downstream consumption, most notably in Blue Ocean.
- [ ] Consider whether to ditch the `testRunName` stuff at the `CaseResult`/`ClassResult` level and instead drive the distinction through a new field in `SuiteResult` (since `SuiteResult.name` already has enough meaning).

cc @reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
How does this relate to #9?

**Comment by abayer** [comment]
Ha, another attempt at a junit step! I'll see what's reusable from there.

**Comment by abayer** [comment]
@jglick Ok, I'd say this supplants #9 - I prefer the approach I'm taking here of reusing/sharing as much logic and behavior between the step and `JUnitResultArchiver` as possible.

**Comment by abayer** [comment]
Closing in favor of #76

**Pull request closed without merging**
