### PR TITLE
URL-encode links to tests

### LINKED ISSUE #659: URL encoding issue in test report links with square brackets
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.479.1
OS: Linux - 6.1.112-124.190.amzn2023.x86_64
Java: 17.0.13 - Amazon.com Inc. (OpenJDK 64-Bit Server VM)
---
<plugins_omitted>
junit:1307.vdd5b_2646279e
<plugins_omitted>
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

After upgrading Jenkins from version 2.462.3 to 2.479.1, all test result/report links containing square brackets ([ and ]) in the URL now fail with the following error:

URI: /badURI
STATUS: 400
MESSAGE: Illegal Path Character

However, if the square brackets are manually replaced with percent encodings (%5B for [ and %5D for ]), the links work correctly.

### Reproduction steps

Access test results/reports via link:
https://<jenkins_url>/job/<job_name>/<build_number>/testReport/(root)/[RESULTS]

### Expected Results

Convert link to this:
https://<jenkins_url>/job/<job_name>/<build_number>/testReport/(root)/%5BRESULTS%5D

### Actual Results

HTTP ERROR 400 Illegal Path Character

URI:	/badURI
STATUS:	400
MESSAGE:	Illegal Path Character

[Powered by Jetty:// 12.0.13](https://jetty.org/)

### Anything else?

_No response_

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by basil**
Fixes #659

### Testing done

- `mvn clean verify`
- Reproduced the problem described in the ticket in Firefox and 2.479.1 before this PR, could no longer reproduce after this PR
- Attempted but failed to write an automated test with HtmlUnit, as I could not reproduce the problem in HtmlUnit but could in Firefox

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by basil** [comment]
@jenkinsci/core-security-review Any objection to this? I can't think of a reason why URL-encoding the test name would be harmful, but maybe I'm missing something here.

**Review by timja — APPROVED** [review]
LGTM

**Comment by ahadalioglu** [comment]
Thanks to everyone who contributed to fixing this bug. However, it’s now replacing spaces with + signs, which breaks the links. Manually replacing + with spaces or %20 makes the links work again. 

NOTE: Previously, only square brackets were an issue, and spaces were untouched.

**Comment by ahadalioglu** [comment]
Thank you to everyone who worked on resolving this issue. I can confirm that the "`All Tests`" link now functions as expected, with all associated links working correctly.

However, links for individual failed test reports (`All Failed Tests`) are still encountering the original issue: square brackets in the URLs are not being replaced with percent-encodings, which still results in link failures. I've attached a screenshot for additional context:
JUnit - SS


Thank you for your continued efforts on this.

**Comment by timja** [comment]
see https://github.com/jenkinsci/junit-plugin/issues/659#issuecomment-2466320063

**Comment by ahadalioglu** [comment]
As I understand it, there's nothing more that can be done regarding the last report, correct? Then we'll rely solely on the 'All Tests' section and avoid using the 'All Failed Tests' section.

Thank you very much, though.
I really appreciate your prompt assistance so far.

**Comment by basil** [comment]
As requested previously, please file a separate ticket for any other places where the URL is not properly encoded, ideally with a PR that resolves the issue.

**Pull request merged**
