### PR TITLE
Add color configuration of trend chart (show passed tests in green or blue )

### PR DESCRIPTION
**Pull request by uhafner**
The new configuration option allows choosing green or blue as color for passed tests:

Bildschirmfoto 2021-08-08 um 23 42 33

Additionally, the stacked chart series have been reordered so that the passed tests come first.
Then the automatic axis scaling of ECharts works as expected and shows only the important chart part. In the screenshot below the x-Axis now starts at 500.

Here is a screenshot of the new layout:
Bildschirmfoto 2021-08-08 um 23 42 17

This PR is an add-on for #272. I will rebase and cleanup this PR after #272 has been merged.

### CODE REVIEW

**Comment by timja** [comment]
Nice we could probably change the default colour to green?

**Comment by uhafner** [comment]
> Nice we could probably change the default colour to green?

Yes, absolutely. This makes more sense for JUnit results (and the build success status is green anyway).

**Comment by timja** [comment]
Some conflicts from the history bug fixes btw.

**Comment by uhafner** [comment]
Yes, I also need to clean up the patch, I forgot to disable IntelliJ's new on save actions. I will do this after the #272 has been merged.

**Comment by timja** [comment]
> Yes, I also need to clean up the patch, I forgot to disable IntelliJ's new on save actions. I will do this after the #272 has been merged.

sure, unlikely code will change much in this area now so any patch should be stable

**Review by timja — APPROVED** [review]
What do think about swapping the default?

**Comment by uhafner** [comment]
I have no strong opinion. Swapping the default would not change the existing visualization, so it might be a better start.

**Comment by timja** [comment]
Ah actually this is the right way round, I just tested it out. Looks good

**Pull request merged**
