### PR TITLE
[FIXED JENKINS-34407] Parse time correctly in SuiteResult.

### PR DESCRIPTION
**Pull request by mfriedenhagen**
* #35 introduced getting suite time from attribute.
* However this did not work correctly when time was > 999.

### CODE REVIEW

**Comment by olivergondza** [comment]
LGTM

**Comment by EamonNerbonne** [comment]
Note that in some cultures, `,` is the decimal seperator.

**Comment by mfriedenhagen** [comment]
Hello, I know, because in Germany we use the comma as well for this. However, the Jenkins plugin has no chance to guess what localization was used while running the tests. The locales of the JVMs runnng Jenkins, Maven and e.g. maven-surefire-plugin might all be different. There is AFAIK no standard attribute in the junit-xml by which we may determine the locale, until now there is not even a common XSD. surefire is always assuming a English locale for time, see https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd

**Comment by EamonNerbonne** [comment]
Well, if that's the case, I'm not convinced it's better to guess at a value than it is to reject uncertain input.  Removing comma's is going to cause weird corruption in some cultures (especially where period is the thousands separator), so it might be simpler to specify on exact serialization and reject everything non-conforming.

**Pull request merged**
