### PR TITLE
Enable release drafter via GitHub action

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Comment by NotMyFault** [comment]
If https://github.com/apps/release-drafter/installations/775283 reports a reliable list of app installations, 151 for me at the moment, I could look forward to bulk PR the action to these repositories via gh cli.

I was messing around earlier with it here: https://github.com/jenkinsci/console-column-plugin/pull/22

**Comment by timja** [comment]
I wrote a dom script, seems to have all of them:

```
Array.from(document.querySelector('#edit_integration_installation_775283 > div > div > div > div.form-checkbox.integrations-install-target.mb-4.clearfix > div > div.integrations-select-repos.js-integrations-install-repo-picked').children).forEach(el => console.log(el.textContent.trim()))
```

```
trilead-ssh2
git-plugin
throttle-concurrent-builds-plugin
gerrit-trigger-plugin
robot-plugin
maven-hpi-plugin
accurev-plugin
build-timeout-plugin
chucknorris-plugin
collapsing-console-sections-plugin
cmakebuilder-plugin
deploy-plugin
extended-read-permission-plugin
email-ext-plugin
github-plugin
gradle-plugin
htmlpublisher-plugin
label-verifier-plugin
mask-passwords-plugin
platformlabeler-plugin
parameterized-trigger-plugin
plot-plugin
mercurial-plugin
role-strategy-plugin
promoted-builds-plugin
swarm-plugin
toolenv-plugin
ssh-slaves-plugin
text-finder-plugin
translation-plugin
view-job-filters-plugin
depgraph-view-plugin
ec2-plugin
lib-test-annotations
lib-annotation-indexer
token-macro-plugin
plugin-compat-tester
ssh-cli-auth-module
config-file-provider-plugin
repo-plugin
ant-plugin
html5-notifier-plugin
github-api-plugin
custom-tools-plugin
build-user-vars-plugin
credentials-plugin
ssh-credentials-plugin
ldap-plugin
pam-auth-plugin
build-blocker-plugin
git-server-plugin
mailer-plugin
mock-security-realm-plugin
ssh-agent-plugin
windows-slave-installer-module
build-failure-analyzer-plugin
stashnotifier-plugin
git-client-plugin
build-token-root-plugin
parallel-test-executor-plugin
ownership-plugin
job-restrictions-plugin
branch-api-plugin
plain-credentials-plugin
credentials-binding-plugin
matrix-combinations-plugin
cloudbees-folder-plugin
support-core-plugin
slack-plugin
lockable-resources-plugin
secure-requester-whitelist-plugin
windows-slaves-plugin
oauth-credentials-plugin
antisamy-markup-formatter-plugin
acceptance-test-harness
metrics-plugin
google-metadata-plugin
figlet-buildstep-plugin
docker
saml-plugin
jsch-plugin
google-login-plugin
jackson-databind-plugin
packaging
docker-commons-plugin
cloudbees-disk-usage-simple-plugin
dockerhub-notification-plugin
docker-workflow-plugin
chatter-notifier-plugin
negotiatesso-plugin
docker-inbound-agent
docker-ssh-agent
docker-agent
ecutest-plugin
github-branch-source-plugin
jackson2-api-plugin
structs-plugin
pipeline-utility-steps-plugin
plugin-pom
blueocean-plugin
bitbucket-branch-source-plugin
workflow-multibranch-plugin
prometheus-plugin
ec2-fleet-plugin
bouncycastle-api-plugin
influxdb-plugin
pipeline-model-definition-plugin
blueocean-display-url-plugin
jms-messaging-plugin
JenkinsPipelineUnit
docker-fixtures
trilead-api-plugin
apache-httpcomponents-client-4-api-plugin
cloudbees-jenkins-advisor-plugin
archetypes
argus-notifier-plugin
command-launcher-plugin
configuration-as-code-plugin
jenkinsfile-runner
jdk-tool-plugin
kubernetes-credentials-provider-plugin
custom-war-packager
code-coverage-api-plugin
additional-metrics-plugin
login-theme-plugin
ssh-steps-plugin
aws-global-configuration-plugin
extended-security-settings-plugin
ci.jenkins.io-runner
core-changelog-generator
templating-engine-plugin
scmskip-plugin
build-symlink-plugin
config-driven-pipeline-plugin
adoptopenjdk-plugin
aws-secrets-manager-credentials-provider-plugin
plugin-installation-manager-tool
atlassian-jira-software-cloud-plugin
graphql-server-plugin
folder-auth-plugin
gitlab-branch-source-plugin
macstadium-orka-plugin
mac-plugin
datetime-constraint-plugin
opencover-plugin
jcasc-vscode-extension
build-health-cache-updater-plugin
metrics-aggregation-plugin
aws-lambda-cloud-plugin
redis-fingerprint-storage-plugin
aws-secrets-manager-secret-source-plugin
```

**Comment by NotMyFault** [comment]
Nice, 151, as reported. Didn't think about DOM here 👀 

If the text proposed is fine, I'd head forward and run it later today.

**Comment by NotMyFault** [comment]
Roughly 100 following repositories from Tim's list received a PR:
```
gerrit-trigger-plugin
robot-plugin
accurev-plugin
build-timeout-plugin
collapsing-console-sections-plugin
cmakebuilder-plugin
deploy-plugin
extended-read-permission-plugin
github-plugin
label-verifier-plugin
mask-passwords-plugin
mercurial-plugin
role-strategy-plugin
toolenv-plugin
translation-plugin
view-job-filters-plugin
depgraph-view-plugin
ec2-plugin
repo-plugin
ant-plugin
html5-notifier-plugin
custom-tools-plugin
build-user-vars-plugin
ssh-credentials-plugin
ldap-plugin
pam-auth-plugin
build-blocker-plugin
git-server-plugin
mock-security-realm-plugin
ssh-agent-plugin
windows-slave-installer-module
build-failure-analyzer-plugin
parallel-test-executor-plugin
ownership-plugin
job-restrictions-plugin
branch-api-plugin
plain-credentials-plugin
credentials-binding-plugin
matrix-combinations-plugin
secure-requester-whitelist-plugin
windows-slaves-plugin
oauth-credentials-plugin
acceptance-test-harness
metrics-plugin
docker
jsch-plugin
google-login-plugin
jackson-databind-plugin
packaging
docker-commons-plugin
dockerhub-notification-plugin
docker-workflow-plugin
chatter-notifier-plugin
negotiatesso-plugin
docker-inbound-agent
docker-ssh-agent
docker-agent
pipeline-utility-steps-plugin
plugin-pom
blueocean-plugin
prometheus-plugin
ec2-fleet-plugin
bouncycastle-api-plugin
influxdb-plugin
JenkinsPipelineUnit
docker-fixtures
trilead-api-plugin
apache-httpcomponents-client-4-api-plugin
archetypes
argus-notifier-plugin
command-launcher-plugin
jdk-tool-plugin
kubernetes-credentials-provider-plugin
custom-war-packager
additional-metrics-plugin
login-theme-plugin
ssh-steps-plugin
aws-global-configuration-plugin
extended-security-settings-plugin
core-changelog-generator
scmskip-plugin
build-symlink-plugin
config-driven-pipeline-plugin
adoptopenjdk-plugin
aws-secrets-manager-credentials-provider-plugin
atlassian-jira-software-cloud-plugin
folder-auth-plugin
gitlab-branch-source-plugin
macstadium-orka-plugin
datetime-constraint-plugin
opencover-plugin
jcasc-vscode-extension
build-health-cache-updater-plugin
aws-lambda-cloud-plugin
redis-fingerprint-storage-plugin
```
Others either have CD enabled or have already a release drafter action set up.

**Comment by jglick** [comment]
As per https://github.com/jenkinsci/mercurial-plugin/pull/199#event-6211153531 can you add a suitable label to each of these please?

**Comment by NotMyFault** [comment]
> As per [jenkinsci/mercurial-plugin#199 (comment)](https://github.com/jenkinsci/mercurial-plugin/pull/199#event-6211153531) can you add a suitable label to each of these please?

I considered doing that, but not every repository has a "chore" label available or labels even set up. Though I could apply it retrospectively to the repositories which do.

**Comment by NotMyFault** [comment]
Incase someone wonders, not every plugin received a PR, either due using CD or already having a release drafter action. These repositories can safely remove the app without further work and are listed below.

<details>
<summary>Repositories that received a PR</summary>

```
gerrit-trigger-plugin
robot-plugin
accurev-plugin
build-timeout-plugin
collapsing-console-sections-plugin
cmakebuilder-plugin
deploy-plugin
extended-read-permission-plugin
github-plugin
label-verifier-plugin
mask-passwords-plugin
mercurial-plugin
role-strategy-plugin
toolenv-plugin
translation-plugin
view-job-filters-plugin
depgraph-view-plugin
ec2-plugin
repo-plugin
ant-plugin
html5-notifier-plugin
custom-tools-plugin
build-user-vars-plugin
ssh-credentials-plugin
ldap-plugin
pam-auth-plugin
build-blocker-plugin
git-server-plugin
mock-security-realm-plugin
ssh-agent-plugin
windows-slave-installer-module
build-failure-analyzer-plugin
parallel-test-executor-plugin
ownership-plugin
job-restrictions-plugin
branch-api-plugin
plain-credentials-plugin
credentials-binding-plugin
matrix-combinations-plugin
secure-requester-whitelist-plugin
windows-slaves-plugin
oauth-credentials-plugin
acceptance-test-harness
metrics-plugin
docker
jsch-plugin
google-login-plugin
jackson-databind-plugin
packaging
docker-commons-plugin
dockerhub-notification-plugin
docker-workflow-plugin
chatter-notifier-plugin
negotiatesso-plugin
docker-inbound-agent
docker-ssh-agent
docker-agent
pipeline-utility-steps-plugin
plugin-pom
blueocean-plugin
prometheus-plugin
ec2-fleet-plugin
bouncycastle-api-plugin
influxdb-plugin
JenkinsPipelineUnit
docker-fixtures
trilead-api-plugin
apache-httpcomponents-client-4-api-plugin
archetypes
argus-notifier-plugin
command-launcher-plugin
jdk-tool-plugin
kubernetes-credentials-provider-plugin
custom-war-packager
additional-metrics-plugin
login-theme-plugin
ssh-steps-plugin
aws-global-configuration-plugin
extended-security-settings-plugin
core-changelog-generator
scmskip-plugin
build-symlink-plugin
config-driven-pipeline-plugin
adoptopenjdk-plugin
aws-secrets-manager-credentials-provider-plugin
atlassian-jira-software-cloud-plugin
folder-auth-plugin
gitlab-branch-source-plugin
macstadium-orka-plugin
datetime-constraint-plugin
opencover-plugin
jcasc-vscode-extension
build-health-cache-updater-plugin
aws-lambda-cloud-plugin
redis-fingerprint-storage-plugin
aws-secrets-manager-secret-source-plugin
templating-engine-plugin
stashnotifier-plugin
```

</details>

<details>
<summary>Repositories that received no PR</summary>

```
trilead-ssh2	
git-plugin	
throttle-concurrent-builds-plugin
maven-hpi-plugin	
chucknorris-plugin	
email-ext-plugin	
gradle-plugin	
htmlpublisher-plugin	
platformlabeler-plugin	
parameterized-trigger-plugin	
plot-plugin
promoted-builds-plugin	
swarm-plugin
ssh-slaves-plugin	
text-finder-plugin
lib-test-annotations	
lib-annotation-indexer	
token-macro-plugin	
plugin-compat-tester	
ssh-cli-auth-module	
config-file-provider-plugin
github-api-plugin	
credentials-plugin	
mailer-plugin	
stashnotifier-plugin	
git-client-plugin	
build-token-root-plugin
cloudbees-folder-plugin	
support-core-plugin	
slack-plugin	
lockable-resources-plugin
antisamy-markup-formatter-plugin	
google-metadata-plugin	
figlet-buildstep-plugin
saml-plugin	
cloudbees-disk-usage-simple-plugin	
ecutest-plugin	
github-branch-source-plugin	
jackson2-api-plugin	
structs-plugin
bitbucket-branch-source-plugin	
workflow-multibranch-plugin
pipeline-model-definition-plugin	
blueocean-display-url-plugin	
jms-messaging-plugin
cloudbees-jenkins-advisor-plugin	
configuration-as-code-plugin	
jenkinsfile-runner
code-coverage-api-plugin	
ci.jenkins.io-runner	
templating-engine-plugin
plugin-installation-manager-tool	
graphql-server-plugin		
mac-plugin	
metrics-aggregation-plugin	
aws-secrets-manager-secret-source-plugin	
```

</details>

**Pull request merged**
