### PR TITLE
Utilize new table style

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed adapts the new table style provided by core.

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did

### CODE REVIEW

**Review by timja — COMMENTED** [review]
Doesn’t this need the minimum version of core increased too?

**Comment by NotMyFault** [comment]
> Doesn’t this need the minimum version of core increased too?

You are right. I, for some reason, was under the impression this change used to be out for much longer. Probably better to keep this on hold then, the next LTS candidate would be the first one to include it anyway.

**Comment by timja** [comment]
There’s no need to hold it back, just update the minimum version to the one it was released in

**Comment by NotMyFault** [comment]
> There’s no need to hold it back, just update the minimum version to the one it was released in

That works too, I wasn't too sure whether that was desired or not.

**Review by timja — APPROVED** [review]

**Comment by uhafner** [comment]
In Jenkins 2.345 the tables have now a rectangular design, is this intended?

Screenshot:

Bildschirmfoto 2022-05-02 um 18 56 51

**Comment by timja** [comment]
I don't think so

**Comment by NotMyFault** [comment]
That indeed is the wrong layout for this kind of table 👀

**Pull request merged**
